/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "byybvazxqfehsdiqfsbn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5eWJ2YXp4cWZlaHNkaXFmc2JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzODk1NDUsImV4cCI6MjA3NTk2NTU0NX0.YbQaZEEz8XxDbJ_a-goUIJawTCuWGBC7ye-UMIT2UVY"